server:
  port: 8082

spring:
  application:
    name: lagou-service-email

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"

email:
  from: zhouzhetian@163.com
  host: smtp.163.com